# Form implementation generated from reading ui file '/Users/german/Code/Python/My Projects/touch-typing-tutorial/src/design/home.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(505, 565)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(12, 12, 12, 12)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.layout_box = QtWidgets.QComboBox(self.centralwidget)
        self.layout_box.setObjectName("layout_box")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.layout_box)
        self.language_box = QtWidgets.QComboBox(self.centralwidget)
        self.language_box.setObjectName("language_box")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.language_box)
        self.gridLayout.addLayout(self.formLayout, 2, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.course_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.course_btn.sizePolicy().hasHeightForWidth())
        self.course_btn.setSizePolicy(sizePolicy)
        self.course_btn.setObjectName("course_btn")
        self.gridLayout_2.addWidget(self.course_btn, 0, 0, 1, 1)
        self.random_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.random_btn.sizePolicy().hasHeightForWidth())
        self.random_btn.setSizePolicy(sizePolicy)
        self.random_btn.setObjectName("random_btn")
        self.gridLayout_2.addWidget(self.random_btn, 1, 0, 1, 1)
        self.texts_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.texts_btn.sizePolicy().hasHeightForWidth())
        self.texts_btn.setSizePolicy(sizePolicy)
        self.texts_btn.setObjectName("texts_btn")
        self.gridLayout_2.addWidget(self.texts_btn, 4, 0, 1, 1)
        self.words_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.words_btn.sizePolicy().hasHeightForWidth())
        self.words_btn.setSizePolicy(sizePolicy)
        self.words_btn.setObjectName("words_btn")
        self.gridLayout_2.addWidget(self.words_btn, 2, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Home — Touch Typing Tutorial"))
        self.label.setText(_translate("MainWindow", "Language: "))
        self.label_2.setText(_translate("MainWindow", "Keyboard Layout: "))
        self.course_btn.setText(_translate("MainWindow", "Basic Course"))
        self.random_btn.setText(_translate("MainWindow", "Random Typing"))
        self.texts_btn.setText(_translate("MainWindow", "Real Texts"))
        self.words_btn.setText(_translate("MainWindow", "Words Typing"))
