# Form implementation generated from reading ui file '/Users/german/Code/Python/My Projects/touch-typing-tutorial/src/design/typing.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(743, 438)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(12, 12, 12, 12)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.input_box = QtWidgets.QLineEdit(Dialog)
        self.input_box.setObjectName("input_box")
        self.horizontalLayout.addWidget(self.input_box)
        self.font_box = QtWidgets.QFontComboBox(Dialog)
        self.font_box.setObjectName("font_box")
        self.horizontalLayout.addWidget(self.font_box)
        self.size_box = QtWidgets.QSpinBox(Dialog)
        self.size_box.setMinimum(1)
        self.size_box.setProperty("value", 18)
        self.size_box.setObjectName("size_box")
        self.horizontalLayout.addWidget(self.size_box)
        self.apply_btn = QtWidgets.QPushButton(Dialog)
        self.apply_btn.setEnabled(False)
        self.apply_btn.setObjectName("apply_btn")
        self.horizontalLayout.addWidget(self.apply_btn)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.lesson_box = QtWidgets.QSpinBox(Dialog)
        self.lesson_box.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.PlusMinus)
        self.lesson_box.setMinimum(1)
        self.lesson_box.setObjectName("lesson_box")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lesson_box)
        self.horizontalLayout_2.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.back_to_menu_btn = QtWidgets.QPushButton(Dialog)
        self.back_to_menu_btn.setAutoDefault(False)
        self.back_to_menu_btn.setObjectName("back_to_menu_btn")
        self.horizontalLayout_2.addWidget(self.back_to_menu_btn)
        self.quit_btn = QtWidgets.QPushButton(Dialog)
        self.quit_btn.setAutoDefault(False)
        self.quit_btn.setObjectName("quit_btn")
        self.horizontalLayout_2.addWidget(self.quit_btn)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.lesson_text = QtWidgets.QTextEdit(Dialog)
        self.lesson_text.setReadOnly(True)
        self.lesson_text.setObjectName("lesson_text")
        self.gridLayout.addWidget(self.lesson_text, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "[name] — Touch Typing Tutorial"))
        self.input_box.setPlaceholderText(_translate("Dialog", "Start Typing..."))
        self.font_box.setCurrentText(_translate("Dialog", "Roboto Mono"))
        self.apply_btn.setText(_translate("Dialog", "Apply"))
        self.label.setText(_translate("Dialog", "Lesson: "))
        self.back_to_menu_btn.setText(_translate("Dialog", "Back to Menu"))
        self.quit_btn.setText(_translate("Dialog", "Quit"))
